In [1]:
import pandas as pd
import numpy as np

In [2]:
np.arange(2,3)

array([2])

In [3]:
np.arange(5,4)

array([], dtype=int32)

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
d1=np.arange(0,15).reshape(3,5)

In [7]:
d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
d=pd.DataFrame(d1,index=['Row1','Row2','Row3'],columns=['column1','column2','column3','column4','column5'])

In [11]:
d

column1  column2  column3  column4  column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14

In [12]:
d.to_csv("Ronnie2")

In [13]:
d.loc['Row3']

column1    10
column2    11
column3    12
column4    13
column5    14
Name: Row3, dtype: int32

In [16]:
d.iloc[1:2,1:2]

column2
Row2        6

In [23]:
url='https://en.wikipedia.org/wiki/Mobile_country_code'
df=pd.read_html(url)

In [24]:
d3=pd.read_excel('Kavita.xlsx')

In [25]:
d3

Name: Department:  Monday  Tuesday  Wednesday  Thursday  Friday  \
0   Joe       Admin       8      7.5          8      8.25    7.75   
1  Jill       Admin       8      8.0          8      7.75    8.00   
2   Jon       Admin       8      0.0          8      8.00    8.00   
3  Jeff       Admin       8      8.0          8      8.00    8.00   

   Total Hours  Net Pay  
0        39.50   343.65  
1        39.75   345.83  
2        32.00   278.40  
3        40.00   348.00

In [29]:
d3

Name: Department:  Monday  Tuesday  Wednesday  Thursday  Friday  \
0   Joe       Admin       8      7.5          8      8.25    7.75   
1  Jill       Admin       8      8.0          8      7.75    8.00   
2   Jon       Admin       8      0.0          8      8.00    8.00   
3  Jeff       Admin       8      8.0          8      8.00    8.00   

   Total Hours  Net Pay  
0        39.50   343.65  
1        39.75   345.83  
2        32.00   278.40  
3        40.00   348.00

In [ ]:
d3